// Auto-generated by VoxCAD FluidX3D node — do not edit manually.
#include "setup.hpp"

void main_setup() { // VoxCAD export; required defines: INTERACTIVE_GRAPHICS, EQUILIBRIUM_BOUNDARIES

	// Simulation box: 29.7 x 13.0 x 13.0 mm
	const uint3 rawN = resolution(float3(1.0000f, 0.4377f, 0.4377f), 1000u);
	const uint3 lbm_N = uint3(((rawN.x+3u)/4u)*4u, ((rawN.y+3u)/4u)*4u, ((rawN.z+3u)/4u)*4u); // round to multiple of 4
	LBM lbm(lbm_N, 0.025000f);
	const uint Nx=lbm.get_Nx(), Ny=lbm.get_Ny(), Nz=lbm.get_Nz();

	// Scale factors: LBM cells per mm
	const float scaleX = (float)Nx / 29.7000f;
	const float scaleY = (float)Ny / 13.0000f;
	const float scaleZ = (float)Nz / 13.0000f;

	// Voxelise solid geometry (STL in mm, centred at world origin)
	const float stl_size = 29.7000f * (float)Nx / 29.7000f;
	lbm.voxelize_stl(get_exe_path()+"../stl/geometry.stl", lbm.center(), float3x3(1.0f), stl_size);

	// Pre-compute BC zone positions in LBM grid cells
	const float3 bc0_center = lbm.center() + float3(
		(-9.0000f - 0.0000f) * scaleX,
		(0.0000f - 0.0000f) * scaleY,
		(0.0000f - 0.0000f) * scaleZ);
	const float  bc0_radius = 5.1000f * scaleX;
	const float  bc0_len    = 0.5000f * scaleX;
	const float3 bc0_axis   = float3(1.0000f, -0.0000f, 0.0000f) * bc0_len;
	const float3 bc1_center = lbm.center() + float3(
		(9.0000f - 0.0000f) * scaleX,
		(0.0000f - 0.0000f) * scaleY,
		(0.0000f - 0.0000f) * scaleZ);
	const float  bc1_radius = 5.1000f * scaleX;
	const float  bc1_len    = 0.5000f * scaleX;
	const float3 bc1_axis   = float3(1.0000f, -0.0000f, 0.0000f) * bc1_len;

	// Apply wall boundaries and BC zones
	parallel_for(lbm.get_N(), [&](ulong n) {
		uint x=0u, y=0u, z=0u; lbm.coordinates(n, x, y, z);

		// Wall on all 6 faces of the simulation box
		if(x==0u||x==Nx-1u||y==0u||y==Ny-1u||z==0u||z==Nz-1u) { lbm.flags[n] = TYPE_S; }

		// BC zone 0: Inlet
		if(cylinder(x, y, z, bc0_center, bc0_axis, bc0_radius)) {
			lbm.flags[n] = TYPE_E;
			lbm.u.x[n] = 0.040000f;
			lbm.u.y[n] = 0.000000f;
			lbm.u.z[n] = 0.000000f;
		}

		// BC zone 1: Outlet
		if(cylinder(x, y, z, bc1_center, bc1_axis, bc1_radius)) {
			lbm.flags[n] = TYPE_E;
		}

	});

	lbm.run(); // interactive graphics: press P to start/pause, H for help
}
